apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
spec:
  serviceName: {{ include "wordpress.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.image.mysql }}
        env:
        - name: MYSQL_DATABASE
          valueFrom: { configMapKeyRef: { name: {{ include "wordpress.fullname" . }}-config, key: WORDPRESS_DB_NAME } }
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: { secretKeyRef: { name: {{ include "wordpress.fullname" . }}-secrets, key: mysql-root-password } }
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.size }}
