apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secrets
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
